version: '3.6'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3.6 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/docker
    ports:
      - "8000:8000"
    depends_on:
      - db