# Generated by Django 2.1.4 on 2018-12-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_by',
        ),
    ]
